-- AI Native Runtime V2.7 M27.1 Product Discovery / Requirement Baseline
-- Migration: 034_product_discovery_requirement_baseline.sql

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS product_research_studies (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  research_key VARCHAR(128) NOT NULL,
  objective TEXT NOT NULL,
  research_question TEXT NOT NULL,
  method VARCHAR(32) NOT NULL,
  participant_segment_json JSON NULL,
  sample_json JSON NOT NULL,
  recruitment_json JSON NULL,
  time_range_json JSON NULL,
  consent_privacy_json JSON NULL,
  recording_boundary_json JSON NULL,
  raw_evidence_locator_json JSON NOT NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  limitation_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_research_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_research_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_research_key (project_id,research_key),
  INDEX idx_m271_research_method (project_id,method,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_evidence (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  research_study_id CHAR(36) NULL,
  evidence_key VARCHAR(128) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_ref VARCHAR(1024) NULL,
  source_date DATE NULL,
  time_range_json JSON NULL,
  segment_json JSON NULL,
  context_json JSON NULL,
  observation TEXT NOT NULL,
  raw_evidence_json JSON NOT NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  limitation_json JSON NULL,
  freshness_expires_at TIMESTAMP(6) NULL,
  privacy_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_evidence_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_evidence_research FOREIGN KEY (research_study_id) REFERENCES product_research_studies(id),
  CONSTRAINT fk_m271_evidence_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_evidence_key (project_id,evidence_key),
  INDEX idx_m271_evidence_source (project_id,source_type,status,source_date),
  INDEX idx_m271_evidence_research (research_study_id),
  INDEX idx_m271_evidence_freshness (project_id,freshness_expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_insights (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  insight_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  observation TEXT NOT NULL,
  user_context_json JSON NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  freshness_expires_at TIMESTAMP(6) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_insight_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_insight_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_insight_key (project_id,insight_key),
  INDEX idx_m271_insight_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_opportunities (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  opportunity_key VARCHAR(128) NOT NULL,
  opportunity_type VARCHAR(32) NOT NULL DEFAULT 'OPPORTUNITY',
  title VARCHAR(255) NOT NULL,
  user_role_json JSON NULL,
  scenario_json JSON NULL,
  pain_opportunity TEXT NOT NULL,
  impact_json JSON NOT NULL,
  existing_workaround_json JSON NULL,
  frequency VARCHAR(32) NULL,
  severity VARCHAR(32) NULL,
  unknowns_json JSON NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_opportunity_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_opportunity_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_opportunity_key (project_id,opportunity_key),
  INDEX idx_m271_opportunity_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_solution_candidates (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  opportunity_id CHAR(36) NOT NULL,
  candidate_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  summary TEXT NOT NULL,
  assumptions_json JSON NULL,
  constraints_json JSON NULL,
  evidence_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CANDIDATE',
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_candidate_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_candidate_opportunity FOREIGN KEY (opportunity_id) REFERENCES product_opportunities(id),
  CONSTRAINT fk_m271_candidate_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_candidate_key (project_id,candidate_key),
  INDEX idx_m271_candidate_opportunity (opportunity_id,status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_hypotheses (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  opportunity_id CHAR(36) NOT NULL,
  solution_candidate_id CHAR(36) NULL,
  hypothesis_key VARCHAR(128) NOT NULL,
  statement TEXT NOT NULL,
  validation_method_json JSON NOT NULL,
  success_signal_json JSON NOT NULL,
  confidence VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_hypothesis_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_hypothesis_opportunity FOREIGN KEY (opportunity_id) REFERENCES product_opportunities(id),
  CONSTRAINT fk_m271_hypothesis_candidate FOREIGN KEY (solution_candidate_id) REFERENCES product_solution_candidates(id),
  CONSTRAINT fk_m271_hypothesis_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_hypothesis_key (project_id,hypothesis_key),
  INDEX idx_m271_hypothesis_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_prioritization_records (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  opportunity_id CHAR(36) NOT NULL,
  hypothesis_id CHAR(36) NULL,
  prioritization_key VARCHAR(128) NOT NULL,
  scoring_model VARCHAR(32) NOT NULL DEFAULT 'CUSTOM',
  score_inputs_json JSON NOT NULL,
  computed_score DECIMAL(20,6) NULL,
  output VARCHAR(32) NOT NULL,
  rationale TEXT NOT NULL,
  decision_id CHAR(36) NOT NULL,
  evidence_json JSON NOT NULL,
  decided_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_priority_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_priority_opportunity FOREIGN KEY (opportunity_id) REFERENCES product_opportunities(id),
  CONSTRAINT fk_m271_priority_hypothesis FOREIGN KEY (hypothesis_id) REFERENCES product_hypotheses(id),
  CONSTRAINT fk_m271_priority_decision FOREIGN KEY (decision_id) REFERENCES project_decisions(id),
  CONSTRAINT fk_m271_priority_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_priority_key (project_id,prioritization_key),
  INDEX idx_m271_priority_output (project_id,output,decided_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_goal_definitions (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  goal_key VARCHAR(128) NOT NULL,
  business_goal TEXT NOT NULL,
  product_goal TEXT NOT NULL,
  primary_metric_json JSON NOT NULL,
  guardrail_metrics_json JSON NULL,
  qualitative_acceptance_json JSON NOT NULL,
  target_window VARCHAR(64) NULL,
  target_version VARCHAR(128) NULL,
  non_goals_json JSON NULL,
  decision_owner_identity_id CHAR(36) NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CURRENT',
  evidence_json JSON NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_goal_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_goal_owner FOREIGN KEY (decision_owner_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_goal_key (project_id,goal_key),
  INDEX idx_m271_goal_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_bets (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  goal_definition_id CHAR(36) NOT NULL,
  opportunity_id CHAR(36) NOT NULL,
  hypothesis_id CHAR(36) NULL,
  bet_key VARCHAR(128) NOT NULL,
  statement TEXT NOT NULL,
  expected_outcome_json JSON NOT NULL,
  constraints_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'APPROVED',
  evidence_json JSON NOT NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_bet_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_bet_goal FOREIGN KEY (goal_definition_id) REFERENCES product_goal_definitions(id),
  CONSTRAINT fk_m271_bet_opportunity FOREIGN KEY (opportunity_id) REFERENCES product_opportunities(id),
  CONSTRAINT fk_m271_bet_hypothesis FOREIGN KEY (hypothesis_id) REFERENCES product_hypotheses(id),
  CONSTRAINT fk_m271_bet_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_bet_key (project_id,bet_key),
  INDEX idx_m271_bet_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_requirements (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  requirement_key VARCHAR(128) NOT NULL,
  requirement_type VARCHAR(32) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  current_version_no INT NOT NULL DEFAULT 1,
  owner_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_requirement_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_requirement_owner FOREIGN KEY (owner_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_requirement_key (project_id,requirement_key),
  INDEX idx_m271_requirement_status (project_id,status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_requirement_versions (
  id CHAR(36) PRIMARY KEY,
  requirement_id CHAR(36) NOT NULL,
  project_id CHAR(36) NOT NULL,
  version_no INT NOT NULL,
  user_role_segment_json JSON NULL,
  scenario_json JSON NOT NULL,
  use_case_job_json JSON NULL,
  business_rules_json JSON NOT NULL,
  preconditions_json JSON NULL,
  main_flow_json JSON NOT NULL,
  alternate_flow_json JSON NULL,
  exception_flow_json JSON NULL,
  state_matrix_json JSON NOT NULL,
  in_scope_json JSON NOT NULL,
  out_of_scope_json JSON NOT NULL,
  assumptions_json JSON NULL,
  open_questions_json JSON NULL,
  priority VARCHAR(16) NOT NULL DEFAULT 'MEDIUM',
  acceptance_criteria_json JSON NOT NULL,
  metric_json JSON NOT NULL,
  dependency_json JSON NULL,
  risk_json JSON NULL,
  evidence_links_json JSON NOT NULL,
  change_id CHAR(36) NULL,
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_req_version_requirement FOREIGN KEY (requirement_id) REFERENCES product_requirements(id),
  CONSTRAINT fk_m271_req_version_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_req_version_change FOREIGN KEY (change_id) REFERENCES project_changes(id),
  CONSTRAINT fk_m271_req_version_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_requirement_version (requirement_id,version_no),
  INDEX idx_m271_req_version_project (project_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_requirement_baselines (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  project_baseline_id CHAR(36) NOT NULL,
  baseline_key VARCHAR(128) NOT NULL,
  goal_definition_id CHAR(36) NOT NULL,
  product_bet_id CHAR(36) NOT NULL,
  requirement_versions_json JSON NOT NULL,
  scope_json JSON NOT NULL,
  business_rules_json JSON NOT NULL,
  acceptance_criteria_json JSON NOT NULL,
  metric_json JSON NOT NULL,
  key_decisions_json JSON NOT NULL,
  out_of_scope_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CURRENT',
  replaced_by_id CHAR(36) NULL,
  evidence_json JSON NOT NULL,
  locked_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_req_baseline_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_req_baseline_project_baseline FOREIGN KEY (project_baseline_id) REFERENCES project_baselines(id),
  CONSTRAINT fk_m271_req_baseline_goal FOREIGN KEY (goal_definition_id) REFERENCES product_goal_definitions(id),
  CONSTRAINT fk_m271_req_baseline_bet FOREIGN KEY (product_bet_id) REFERENCES product_bets(id),
  CONSTRAINT fk_m271_req_baseline_replaced FOREIGN KEY (replaced_by_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m271_req_baseline_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_req_baseline_key (project_id,baseline_key),
  UNIQUE KEY uq_m271_req_baseline_project_baseline (project_baseline_id),
  INDEX idx_m271_req_baseline_status (project_id,status,locked_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_trace_links (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  source_type VARCHAR(64) NOT NULL,
  source_id CHAR(36) NOT NULL,
  target_type VARCHAR(64) NOT NULL,
  target_id CHAR(36) NOT NULL,
  link_type VARCHAR(64) NOT NULL,
  evidence_json JSON NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_trace_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_trace_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m271_trace (project_id,source_type,source_id,target_type,target_id,link_type),
  INDEX idx_m271_trace_source (project_id,source_type,source_id),
  INDEX idx_m271_trace_target (project_id,target_type,target_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_gate_evaluations (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  gate_key VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  reason_codes_json JSON NOT NULL,
  evidence_snapshot_json JSON NOT NULL,
  as_of TIMESTAMP(6) NOT NULL,
  evaluated_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m271_gate_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m271_gate_identity FOREIGN KEY (evaluated_by_identity_id) REFERENCES identities(id),
  INDEX idx_m271_gate_project (project_id,gate_key,as_of),
  INDEX idx_m271_gate_status (gate_key,status,as_of)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
