-- AI Native Runtime V2.7 M27.2 Feasibility / Delivery / Design / Technical Contract
-- Migration: 035_product_design_technical_contract.sql

SET NAMES utf8mb4;
SET time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS product_feasibility_reviews (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  product_baseline_id CHAR(36) NOT NULL,
  review_key VARCHAR(128) NOT NULL,
  overall_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
  section_status_json JSON NOT NULL,
  architecture_json JSON NOT NULL,
  framework_runtime_json JSON NOT NULL,
  data_json JSON NOT NULL,
  api_integration_json JSON NOT NULL,
  auth_permission_json JSON NOT NULL,
  security_privacy_compliance_json JSON NOT NULL,
  performance_scalability_json JSON NOT NULL,
  reliability_availability_json JSON NOT NULL,
  deployment_migration_json JSON NOT NULL,
  third_party_dependency_json JSON NOT NULL,
  cost_quota_json JSON NOT NULL,
  observability_supportability_json JSON NOT NULL,
  rollback_json JSON NOT NULL,
  risk_summary_json JSON NOT NULL,
  architecture_decision_required BOOLEAN NOT NULL DEFAULT FALSE,
  skipped_reason TEXT NULL,
  approval_decision_id CHAR(36) NULL,
  evidence_json JSON NOT NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_feasibility_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_feasibility_baseline FOREIGN KEY (product_baseline_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m272_feasibility_decision FOREIGN KEY (approval_decision_id) REFERENCES project_decisions(id),
  CONSTRAINT fk_m272_feasibility_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_feasibility_key (project_id,review_key),
  INDEX idx_m272_feasibility_status (project_id,overall_status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_architecture_decisions (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  feasibility_review_id CHAR(36) NOT NULL,
  product_baseline_id CHAR(36) NOT NULL,
  adr_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  context_json JSON NOT NULL,
  options_json JSON NOT NULL,
  decision_json JSON NOT NULL,
  consequences_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED',
  project_decision_id CHAR(36) NOT NULL,
  effective_version VARCHAR(128) NULL,
  evidence_json JSON NOT NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_adr_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_adr_feasibility FOREIGN KEY (feasibility_review_id) REFERENCES product_feasibility_reviews(id),
  CONSTRAINT fk_m272_adr_baseline FOREIGN KEY (product_baseline_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m272_adr_decision FOREIGN KEY (project_decision_id) REFERENCES project_decisions(id),
  CONSTRAINT fk_m272_adr_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_adr_key (project_id,adr_key),
  INDEX idx_m272_adr_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_delivery_plans (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  product_baseline_id CHAR(36) NOT NULL,
  feasibility_review_id CHAR(36) NOT NULL,
  plan_key VARCHAR(128) NOT NULL,
  target_release_version_id CHAR(36) NOT NULL,
  milestone_ids_json JSON NOT NULL,
  iteration_ids_json JSON NOT NULL,
  work_item_ids_json JSON NOT NULL,
  dependency_ids_json JSON NOT NULL,
  capacity_snapshot_ids_json JSON NOT NULL,
  critical_path_json JSON NOT NULL,
  release_sequence_json JSON NOT NULL,
  definition_of_done_json JSON NOT NULL,
  acceptance_plan_json JSON NOT NULL,
  risk_blocker_plan_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'CURRENT',
  evidence_json JSON NOT NULL,
  replaced_by_id CHAR(36) NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_plan_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_plan_baseline FOREIGN KEY (product_baseline_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m272_plan_feasibility FOREIGN KEY (feasibility_review_id) REFERENCES product_feasibility_reviews(id),
  CONSTRAINT fk_m272_plan_release FOREIGN KEY (target_release_version_id) REFERENCES project_versions(id),
  CONSTRAINT fk_m272_plan_replaced FOREIGN KEY (replaced_by_id) REFERENCES product_delivery_plans(id),
  CONSTRAINT fk_m272_plan_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_plan_key (project_id,plan_key),
  INDEX idx_m272_plan_status (project_id,status,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_design_contracts (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  contract_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  current_version_no INT NOT NULL DEFAULT 1,
  owner_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_design_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_design_owner FOREIGN KEY (owner_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_design_key (project_id,contract_key),
  INDEX idx_m272_design_status (project_id,status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_design_contract_versions (
  id CHAR(36) PRIMARY KEY,
  design_contract_id CHAR(36) NOT NULL,
  project_id CHAR(36) NOT NULL,
  product_baseline_id CHAR(36) NOT NULL,
  version_no INT NOT NULL,
  source_locator_json JSON NOT NULL,
  source_verification_json JSON NOT NULL,
  design_system_locator_json JSON NULL,
  information_architecture_json JSON NOT NULL,
  user_flows_json JSON NOT NULL,
  screens_pages_json JSON NOT NULL,
  components_json JSON NOT NULL,
  tokens_style_json JSON NOT NULL,
  interaction_json JSON NOT NULL,
  state_matrix_json JSON NOT NULL,
  responsive_adaptive_json JSON NOT NULL,
  accessibility_json JSON NOT NULL,
  content_copy_json JSON NOT NULL,
  platform_behavior_json JSON NOT NULL,
  prototype_locator_json JSON NOT NULL,
  design_acceptance_matrix_json JSON NOT NULL,
  change_id CHAR(36) NULL,
  evidence_json JSON NOT NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_design_version_contract FOREIGN KEY (design_contract_id) REFERENCES product_design_contracts(id),
  CONSTRAINT fk_m272_design_version_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_design_version_baseline FOREIGN KEY (product_baseline_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m272_design_version_change FOREIGN KEY (change_id) REFERENCES project_changes(id),
  CONSTRAINT fk_m272_design_version_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_design_version (design_contract_id,version_no),
  INDEX idx_m272_design_version_project (project_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_technical_contracts (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  contract_key VARCHAR(128) NOT NULL,
  title VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  current_version_no INT NOT NULL DEFAULT 1,
  owner_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_technical_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_technical_owner FOREIGN KEY (owner_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_technical_key (project_id,contract_key),
  INDEX idx_m272_technical_status (project_id,status,updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_technical_contract_versions (
  id CHAR(36) PRIMARY KEY,
  technical_contract_id CHAR(36) NOT NULL,
  project_id CHAR(36) NOT NULL,
  product_baseline_id CHAR(36) NOT NULL,
  design_contract_version_id CHAR(36) NULL,
  version_no INT NOT NULL,
  technical_design_json JSON NOT NULL,
  api_contract_json JSON NOT NULL,
  data_contract_json JSON NOT NULL,
  integration_contract_json JSON NOT NULL,
  instrumentation_contract_json JSON NOT NULL,
  section_status_json JSON NOT NULL,
  change_id CHAR(36) NULL,
  evidence_json JSON NOT NULL,
  created_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_technical_version_contract FOREIGN KEY (technical_contract_id) REFERENCES product_technical_contracts(id),
  CONSTRAINT fk_m272_technical_version_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_technical_version_baseline FOREIGN KEY (product_baseline_id) REFERENCES product_requirement_baselines(id),
  CONSTRAINT fk_m272_technical_version_design FOREIGN KEY (design_contract_version_id) REFERENCES product_design_contract_versions(id),
  CONSTRAINT fk_m272_technical_version_change FOREIGN KEY (change_id) REFERENCES project_changes(id),
  CONSTRAINT fk_m272_technical_version_creator FOREIGN KEY (created_by_identity_id) REFERENCES identities(id),
  UNIQUE KEY uq_m272_technical_version (technical_contract_id,version_no),
  INDEX idx_m272_technical_version_project (project_id,created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS product_m272_gate_evaluations (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  gate_key VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  reason_codes_json JSON NOT NULL,
  evidence_snapshot_json JSON NOT NULL,
  as_of TIMESTAMP(6) NOT NULL,
  evaluated_by_identity_id CHAR(36) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_m272_gate_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_m272_gate_identity FOREIGN KEY (evaluated_by_identity_id) REFERENCES identities(id),
  INDEX idx_m272_gate_project (project_id,gate_key,as_of),
  INDEX idx_m272_gate_status (gate_key,status,as_of)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
