CREATE TABLE IF NOT EXISTS requirement_completion_sessions (
  id CHAR(36) PRIMARY KEY,
  project_id CHAR(36) NOT NULL,
  workspace_id CHAR(36) NOT NULL,
  actor_key VARCHAR(191) NOT NULL,
  source_statement TEXT NOT NULL,
  application_type VARCHAR(32) NOT NULL DEFAULT 'UNSPECIFIED',
  status VARCHAR(32) NOT NULL,
  context_fingerprint CHAR(64) NOT NULL,
  run_id CHAR(36) NOT NULL,
  task_id CHAR(36) NOT NULL,
  step_id CHAR(36) NOT NULL,
  model_provider VARCHAR(80) NULL,
  model_key VARCHAR(191) NULL,
  provider_response_id VARCHAR(191) NULL,
  input_tokens BIGINT NULL,
  output_tokens BIGINT NULL,
  total_tokens BIGINT NULL,
  result_json JSON NULL,
  decisions_json JSON NOT NULL,
  prd_handoff_json JSON NULL,
  error_code VARCHAR(120) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_requirement_completion_project FOREIGN KEY (project_id) REFERENCES projects(id),
  CONSTRAINT fk_requirement_completion_workspace FOREIGN KEY (workspace_id) REFERENCES workspaces(id),
  INDEX idx_requirement_completion_project_created (project_id, created_at),
  INDEX idx_requirement_completion_project_status (project_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
